title: Eduard de Vidal Flores
logo: /assets/images/profilepicture.jpg
description: |
  Game programmer and software engineer with experience in C++ (OpenGL, Qt) and Unity (C#), and an array of projects to prove my skills.
  Strong education, including a double bachelor's degree in mathematics and CS (UPC-CFIS) and a game research stay at MIT.
  #Research Visiting Student @ MIT | Bachelor's in CS & Math
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme